# Generated by Django 2.2.2 on 2019-06-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('0', 'OBGYN'), ('1', 'PT'), ('2', 'ER'), ('3', 'FM')], default='FM', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date visited')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Physician')),
            ],
        ),
    ]
