# Generated by Django 2.2.2 on 2019-06-30 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='physician',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='physician',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
