# Generated by Django 2.2.2 on 2019-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20190630_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
